# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0


  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install  \
            gfortran            \
            libblas-dev         \
            liblapack-dev       \
            openmpi-bin         \
            libopenmpi-dev
          pip install --upgrade pip
          pip install   \
            numpy       \
            matplotlib  \
      - name: build
        run:  |
          cd optados 
          make 
          make tools
      - name: run tests
        run: |
          cd optados/test-suite
          ./run_tests -v --category=default 

